env:
language: node_js
node_js:
  - "node"
before_script:
  - npm run build
cache:
  directories:
    - "node_modules"
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: pogosticks.party
  skip_cleanup: true
  local_dir: build
  cache_control: "max-age=21600"
